export enum RabbitMQ {
  PassengerQueue = 'passengers',
}
export enum PassengerMSG {
  INSERTAR = 'CREAR_PASAJERO',
  TODOS = 'TODOS_LOS_PASAJEROS',
  UNO = 'UN_PASAJERO',
  ACTUALIZAR = 'ACTUALIZA_PASAJERO',
  ELIMINAR = 'ELIMINAR_PASAJERO',
  VALIDAR_USAURIO = 'VALIDAR_PASAJERO',
}
